@host = http://localhost:3000/auth

### 회원가입(유저)
POST {{host}}/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "example1234@example.com",
  "name": "유저 이름",
  "auth": "6713",
  "password": "ExAmple123!",
  "passwordCheck": "ExAmple123!"
}

### 회원가입(펫시터)
POST {{host}}/petsitters/signup HTTP/1.1
Content-Type: application/json

{
  "email": "petsitter5@example.com",
  "name": "강형욱",
  "career": "2년",
  "tags":"태그1,태그2,태그3",
  "password": "ExAmple123!",
  "passwordCheck": "ExAmple123!"
}


### 로그인(유저)
POST {{host}}/users/login
Content-Type: application/json

{
  "email": "abc29887@naver.com",
  "password": "asdfasdf"
}

### 로그인(펫시터)
POST {{host}}/petsitters/login
Content-Type: application/json

{
  "email": "petsitter12@example.com",
  "password": "ExAmple123!"
}

### 내 정보 조회
GET  {{host}}/me

### 유저 상세 조회
GET  {{host}}/users

### 로그아웃
GET {{host}}/logout

### 돈 충전하기
POST {{host}}/users/charge
Content-Type: application/json

{
  "money": 10000
} 