@host = http://localhost:3000/petsitters

### 펫시터 조회
GET {{host}}/ HTTP/1.1
Content-Type: application/json

### 펫시터 상세 조회
GET {{host}}/1  HTTP/1.1
Content-Type: application/json

### 펫시터 검색
GET {{host}}/search?keyword=이름  HTTP/1.1
Content-Type: application/json
